### ISSUE TITLE
androidx migrated release

### ISSUE THREAD

**Issue by simonpoole** [heinrichreimer/android-issue-reporter#132]
Hi, would it possible to create a release with the current androidx migrated code? 

Due to restrictions by F-Droid we (https://github.com/MarcusWolschon/osmeditor4android/) can only include dependencies that are published on one of the major binaries repos, so without a release I have to fork the project and publish it myself, which is a royal PITA and a waste of time.

Thank you for your consideration.

**Comment by heinrichreimer** [comment]
There you go: https://github.com/heinrichreimer/android-issue-reporter/releases/tag/1.4
No guarantees if it works, though 😢

**Comment by simonpoole** [comment]
Looks good, thanks a lot.
