### ISSUE TITLE
Allow text copy of device info in github issue

### ISSUE THREAD

**Issue by HolgerJeromin** [heinrichreimer/android-issue-reporter#135]
Create github issue
Look at the device info (geräteinfo).
Would be nice if I could select and copy the device details.

**Comment by heinrichreimer** [comment]
You mean on the reporting device?

**Comment by HolgerJeromin** [comment]
yes

**Comment by cyb3rko** [comment]
We could just set the TextView holding the device info to support text selection.  
Would that be enough?

**Comment by heinrichreimer** [comment]
Yes, I think so.
