### ISSUE TITLE
1.4.1 not building on jitpack

### ISSUE THREAD

**Issue by simonpoole** [heinrichreimer/android-issue-reporter#157]
See https://jitpack.io/com/heinrichreimersoftware/android-issue-reporter/1.4.1/build.log

**Comment by cyb3rko** [comment]
I would guess incompatible JDK version.  
Maybe first step would be adding this to build.gradle:

https://github.com/cyb3rko/quick-permissions-kotlin/blob/54f31ceb6f4e4c243efefc3fffb4b8195d6eae11/quickpermissions-kotlin/build.gradle#L21-L27

**Comment by simonpoole** [comment]
I think https://jitpack.io/docs/BUILDING/#java-version is likely the issue, at least I couldn't find any reference in the docs that they use the values specified in the gradle build file.

With other words adding a jitpack.yml specifiying java 17 should do the trick.
