### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by Xstar97** [HeinrichReimer/android-issue-reporter#28]
I been using gitty reporter & planning on switching since its not maintained anymore....I designed a way if my app crashes it creates a stack.trace & when the use relaunches my app...it will ask if they want to report the crash(thread started from mainactivity which checks for a crash boolean from prefs/also other info too!)
so then the user launches gitty report & another dialog pop ups asking the user to copy the stack.trace on positive click

However this does work very well & am glad that it does(However not a single user has used it yet!)
But, I was wondering if its possible to attach the stack.trace automatically without any user interaction or (maybe) via checkbox when selected or automatically selected.
Issues can accept files so I was wondering if you will implement this & if you do I am totally switching to your library instead.

**Comment by HeinrichReimer** [comment]
You could do that by overriding `onSaveExtraInfo()`:

```java
@Override
public void onSaveExtraInfo(ExtraInfo extraInfo) {
    StringWriter sw = new StringWriter();
    PrintWriter pw = new PrintWriter(sw);
    yourException.printStackTrace(pw);
    extraInfo.put("Exception", sw.toString());
}
```

Also feel free to create a pull request with this as a convenience method so that we can call `ExtraInfo. put(String key, Throwable t)` directly.

Automated crash detection and logging however goes way beyond this library's scale as it requires a lot of bloating extra code.

**Comment by Xstar97** [comment]
I have already made the code for automated crash detection...however I use a lot of dialogs for user interface & I just want to clean it up & i dont want the ask users if they want to copy the stack trace anymore(some users got confused on what it was & uninstalled my tool...)...so thanks...I will implement this in my app some time today

**Comment by HeinrichReimer** [comment]
If I understand you right that option should be a setting in a separate settings page to toggle an opt-out.
