### ISSUE TITLE
Support for Gitlab

### ISSUE THREAD

**Issue by AkshayChordiya** [heinrichreimer/android-issue-reporter#41]

**Comment by HeinrichReimer** [comment]
Yeah, that would be awesome

**Comment by HeinrichReimer** [comment]
Would also be great to have it integrated with BitBucket

**Comment by HeinrichReimer** [comment]
If you know any API, that would be useful

**Comment by AkshayChordiya** [comment]
Gitlab Client API:
[http://docs.gitlab.com/ce/api/](url)

**Comment by HeinrichReimer** [comment]
Do they have a Java wrapper too or just the REST API?

**Comment by AkshayChordiya** [comment]
@HeinrichReimer 
Yeah there is an unofficial Java Wrapper. It's unofficial but is shown in on their website itself.
Here is the link to it [https://github.com/timols/java-gitlab-api](url)

**Comment by AkshayChordiya** [comment]
@HeinrichReimer 
Will the Java wrapper which I gave above be useful for Gitlab support?

**Comment by AkshayChordiya** [comment]
@HeinrichReimer 
Any ETA for release of 2.0

**Comment by AkshayChordiya** [comment]
@HeinrichReimer Maybe I'll try to create a pull request with Gitlab wrapper?

**Comment by HeinrichReimer** [comment]
Thing is that in order to get this to work we would need to make the whole project abstract so that one could use different wrappers for different services.

**Comment by HeinrichReimer** [comment]
This is pretty much work

**Comment by HeinrichReimer** [comment]
Another option may be to fork the project and entirely replace the GitHub implementation with the GitLab one.

**Comment by AkshayChordiya** [comment]
@HeinrichReimer I understand. I think we should create a separate project.
