### ISSUE TITLE
Bot Key

### ISSUE THREAD

**Issue by ghost** [HeinrichReimer/android-issue-reporter#43]
Hi, I've just implemented your library and i would like to know how do you make a bot key so people can post without a github account

**Comment by HeinrichReimer** [comment]
1.  Create a new GitHub account. _(You have to use a unique email address.)_
2.  Go to https://github.com/settings/tokens and create a new token using <kbd>Generate new token</kbd>. _(You don't need to give the bot any other rights than posting issues.)_
3.  Copy the OAuth access token you get at the end of the setup
4.  Override `getGuestToken()` like this:

    ```java
    @Override
    public String getGuestToken() {
        return "<your token here>";
    }
    ```

**Comment by HeinrichReimer** [comment]
1.  Create a new GitHub account. _(You have to use a unique email address.)_
2.  Go to https://github.com/settings/tokens and create a new token using <kbd>Generate new token</kbd>. _(You don't need to give the bot any other rights than posting issues.)_
3.  Copy the OAuth access token you get at the end of the setup
4.  Override `getGuestToken()` like this:

    ```java
    @Override
    public String getGuestToken() {
        return "<your token here>";
    }
    ```

**Comment by HeinrichReimer** [comment]
I'll close this issue once I add this description to the `README.md`.

**Comment by ronaldsmartin** [comment]
Hi @HeinrichReimer, thanks for making this library!

While the instructions you added here went a long way toward helping me create a bot to use with the library, I ended up getting stuck for a bit trying to figure out which of the available permissions would allow the bot to create issues.

It might help to clarify in the docs that the permission required for this (on open source repos, at least) is the `public_repo` permission.

Thanks again!

**Comment by HeinrichReimer** [comment]
Clarified that in the README (see 269f6fc57d11e27dd0496be039cab194b6d25425).
