### ISSUE TITLE
Error: more than one library with package name 'com.afollestad.materialdialogs'

### ISSUE THREAD

**Issue by Nielssg** [HeinrichReimer/android-issue-reporter#46]
Hi,
I am getting this error:

    Error:Execution failed for task ':app:processDebugResources'.
    > Error: more than one library with package name 'com.afollestad.materialdialogs'

I've tried finding out where it came from, and I eventually landed on this plugin. I tried editing proguard rules, tried removing material dialogs, tried this: android.enforceUniquePackageName = false. But nothing worked.

How can I fix this?

**Comment by himanhsusehgal** [comment]
i am getting same error anyone can help me?

**Comment by heinrichreimer** [comment]
Check your app's dependencies using `gradle dependencies`. If material-dialogs appears twice with different versions, try to resolve that version conflict.
