### ISSUE TITLE
Huidige Tijd

### ISSUE THREAD

**Issue by lbphond** [HeinrichReimer/android-issue-reporter#47]
Geef weer wanneer de huidige tijd is, door bijvoorbeeld de tekst bold te maken

-

Device info:
---
<table>
<tr><td>App version</td><td>1.4</td></tr>
<tr><td>App version code</td><td>33</td></tr>
<tr><td>Android build version</td><td>3079158</td></tr>
<tr><td>Android release version</td><td>5.1.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>sdk_google_phone_x86-userdebug 5.1.1 LMY48X 3079158 test-keys</td></tr>
<tr><td>Device brand</td><td>Android</td></tr>
<tr><td>Device manufacturer</td><td>unknown</td></tr>
<tr><td>Device name</td><td>generic_x86</td></tr>
<tr><td>Device model</td><td>Android SDK built for x86</td></tr>
<tr><td>Device product name</td><td>sdk_google_phone_x86</td></tr>
<tr><td>Device hardware name</td><td>ranchu</td></tr>
<tr><td>ABIs</td><td>[x86]</td></tr>
<tr><td>ABIs (32bit)</td><td>[x86]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Test 1</td><td>Example string</td></tr>
<tr><td>Test 2</td><td>true</td></tr>
</table>

**Comment by Nielssg** [comment]
Wrong repository bro :P
