### ISSUE TITLE
more features

### ISSUE THREAD

**Issue by Xstar97** [HeinrichReimer/android-issue-reporter#48]
It will be awesome if you could implement more translations...like spanish, german, french, etc.
Also if someone uses their account to send an issue...it will save time if the account was automatically (safely & securely) saved for future issue reporting.

**Comment by HeinrichReimer** [comment]
To provide more translations please create a pull request adding the specific `values-XX/strings.xml` files where `XX` is the Android country resource modifier.

**Comment by HeinrichReimer** [comment]
Saving the account information would blow up this library too much as we would need to provide an encrypted storage for the account password, something that this library definitely not claims to deal with. If entering their account name and password is too hard for your users you can enable them to just put in an email address to identify.
