### ISSUE TITLE
Migrating to MIT license

### ISSUE THREAD

**Issue by HeinrichReimer** [HeinrichReimer/android-issue-reporter#61]
As the MIT is easier to include for developers using this library I want to change the library license from Apache license 2.0 to the more permissive and simpler MIT license.
Because the license change would give library users more permissions than with the APLv2 all contributors need to approve this change.

Here's a list of all contributors to keep track of all confirmations:
- [x] @HeinrichReimer 
- [x] @paolorotolo 
- [x] @rosenpin 
- [x] @pinpong 
- [x] @rotolonico 
- [x] @kabouzeid 
- [x] @patrick91 
- [x] @RiccardoBusetti 

I'll notify the contributors so that we can change the license ASAP.

**Comment by paolorotolo** [comment]
I'm ok with the change :+1:

**Comment by rosenpin** [comment]
Not sure if you missed my email.

Sure, I think that's a good idea.

**Comment by HeinrichReimer** [comment]
@rosenpin I didn't get any email from you... Probably it's just in the spam folder mistakenly but thank you for commenting here to approve the license change!
