### ISSUE TITLE
Add spanish translation

### ISSUE THREAD

**Issue by edxavier** [heinrichreimer/android-issue-reporter#72]
Seria bueno que dieras la opción para establecer los textos de la interfaces ya que el único idioma es ingles y no encontre como cambiar o poner textos personalizados, gracias

**Comment by heinrichreimer** [comment]
If you want to translate _android-issue-reporter_ feel free to do so in a pull request.
(Check #9 for an example PR from the Italian translation.)

**Comment by heinrichreimer** [comment]
@edxavier Sorry if I misunderstood you, I don't speak Spanish so I can only rely on the power of Google translate 😆
